SELECT K.ENTER_CD AS "회사코드"
       ,(SELECT F_COM_GET_ENTER_NM(K.ENTER_CD, DECODE('@ssnLocaleCd@', 'en_US', '2', '1')) FROM DUAL) AS "회사명"
       ,K.SABUN AS "사번"
       ,F_COM_GET_NAMES(K.ENTER_CD, K.SABUN) AS "성명"
       ,CRYPTIT.DECRYPT(K.RES_NO, K.ENTER_CD) AS "주민번호"
       ,(SELECT F_COM_GET_GRCODE_NAME(C.ENTER_CD, 'H00010', K.SEX_TYPE, '@ssnLocaleCd@') FROM DUAL) AS "성별"
       ,F_COM_GET_NAMES(K.ENTER_CD, K.SABUN, 'zh_CN') AS "한자성명"
       ,F_COM_GET_NAMES(K.ENTER_CD, K.SABUN, 'en_US') AS "영문성명"
       ,TO_CHAR(TO_DATE(K.GEMP_YMD, 'YYYYMMDD'), 'YYYY-MM-DD') AS "그룹입사일"
       ,TO_CHAR(TO_DATE(K.EMP_YMD, 'YYYYMMDD'), 'YYYY-MM-DD') AS "입사일"
       ,F_COM_GET_CAREER_CNT(K.ENTER_CD, K.SABUN, 'W', 'YYMM', '1', NULL, '@ssnLocaleCd@') AS "근속기간"
       ,F_COM_GET_CAREER_CNT(K.ENTER_CD, K.SABUN, 'Y', 'YYMM', '1', NULL, '@ssnLocaleCd@') AS "근속기간경력포함"
       ,K.CAREER_YY_CNT AS "인정경력년"
       ,K.CAREER_MM_CNT AS "인정경력개월"
       ,TO_CHAR(TO_DATE(K.RET_YMD, 'YYYYMMDD'), 'YYYY-MM-DD') AS "퇴사일"
       ,K.TRA_YMD AS "면수습일"
       ,F_COM_GET_MAP_CD(K.ENTER_CD, '100', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "급여사업장코드"
       ,F_COM_GET_MAP_NM(K.ENTER_CD, '100', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "급여사업장명"
       ,F_COM_GET_MAP_ORGLEVEL_CD(K.ENTER_CD, '100', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "사업장코드"
       ,F_COM_GET_MAP_ORGLEVEL_NM(K.ENTER_CD, '100', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "사업장명"
       ,F_COM_GET_MAP_CD(K.ENTER_CD, '300', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "코스트센터코드"
       ,F_COM_GET_MAP_NM(K.ENTER_CD, '300', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "코스트센터명"
       ,F_COM_GET_MAP_CD(K.ENTER_CD, '500', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "근무조코드"
       ,F_COM_GET_MAP_NM(K.ENTER_CD, '500', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "근무조명"
       ,F_COM_GET_MAP_CD(K.ENTER_CD, '600', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "LOCATION코드"
       ,F_COM_GET_MAP_NM(K.ENTER_CD, '600', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "LOCATION명"
       ,F_COM_GET_MAP_CD(K.ENTER_CD, '700', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "조직유형코드"
       ,F_COM_GET_MAP_NM(K.ENTER_CD, '700', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "조직유형명"
       ,F_COM_GET_MAP_CD(K.ENTER_CD, '800', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "근무지코드"
       ,F_COM_GET_MAP_NM(K.ENTER_CD, '800', K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "근무지명"
       ,(SELECT NVL(F_COM_GET_HQ_ORG_NM(K.ENTER_CD, C.ORG_CD, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), 'B0400'), F_COM_GET_HQ_ORG_NM(K.ENTER_CD, C.ORG_CD, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), 'B0300')) FROM DUAL) AS "본부명"
       ,C.ORG_CD AS "부서코드"
       ,(SELECT F_COM_GET_ORG_NM(C.ENTER_CD, C.ORG_CD, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') FROM DUAL) AS "부서명"
       ,C.STATUS_CD AS "재직상태코드"
       ,(SELECT F_COM_GET_GRCODE_NAME(C.ENTER_CD, 'H10010', C.STATUS_CD, '@ssnLocaleCd@') FROM DUAL) AS "재직상태명"
       ,C.MANAGE_CD AS "직군코드" /*30 OLD사원구분코드*/
       ,(SELECT F_COM_GET_GRCODE_NAME(C.ENTER_CD, 'H10030', C.MANAGE_CD, '@ssnLocaleCd@') FROM DUAL)  AS "직군" /*31 OLD사원구분명*/
       ,C.JIKGUB_CD AS "JOB_BAND_코드" /*32 OLD직급코드*/
       ,(SELECT F_COM_GET_GRCODE_NAME(C.ENTER_CD, 'H20010', C.JIKGUB_CD, '@ssnLocaleCd@') FROM DUAL)  AS "JOB_BAND" /*33 OLD직급명*/
       ,C.JIKWEE_CD AS "KOREAN_TITLE_코드" /*34 OLD직위코드*/
       ,(SELECT F_COM_GET_GRCODE_NAME(C.ENTER_CD, 'H20030', C.JIKWEE_CD, '@ssnLocaleCd@') FROM DUAL)  AS "KOREAN_TITLE" /*35 OLD직위명*/
       ,C.JIKCHAK_CD AS "TITLE_코드" /*36 OLD직책코드*/
       ,(SELECT F_COM_GET_GRCODE_NAME(C.ENTER_CD, 'H20020', C.JIKCHAK_CD, '@ssnLocaleCd@') FROM DUAL)  AS "TITLE" /*37 OLD직책명*/
       ,F_COM_GET_TITLE_JOB_CD(C.ENTER_CD, K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "직무코드"
       ,F_COM_GET_TITLE_JOB_NM(C.ENTER_CD, K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "직무"
       ,C.WORK_TYPE AS "FUNCTION_코드" /*40 OLD직군코드*/
       ,(SELECT F_COM_GET_GRCODE_NAME(C.ENTER_CD, 'H10050', C.WORK_TYPE, '@ssnLocaleCd@') FROM DUAL)  AS "FUNCTION명" /*41 OLD직군명*/
       ,C.BASE1_CD AS "SUB_FUNCTION_코드"
       ,C.BASE1_NM AS "SUB_FUNCTION명"
       ,C.POSITION_TITLE_CD AS "POSITION_TITLE_코드"
       ,(SELECT F_COM_GET_GRCODE_NAME(C.ENTER_CD, 'H20020', C.POSITION_TITLE_CD, '@ssnLocaleCd@') FROM DUAL) AS "POSITION_TITLE"
       ,C.POSITION_BAND_CD AS "POSITION_BAND_코드"
       ,(SELECT F_COM_GET_GRCODE_NAME(C.ENTER_CD, 'H20010', C.POSITION_BAND_CD, '@ssnLocaleCd@') FROM DUAL) AS "POSITION_BAND"
       ,C.PERSONAL_BAND_CD AS "PERSONAL_BAND_코드"
       ,(SELECT F_COM_GET_GRCODE_NAME(C.ENTER_CD, 'H20010', C.PERSONAL_BAND_CD, '@ssnLocaleCd@') FROM DUAL) AS "PERSONAL_BAND"
       ,TO_CHAR(TO_DATE(F_COM_GET_CURR_POSITION_BAND_YMD(K.ENTER_CD, K.SABUN, TO_CHAR(SYSDATE, 'YYYYMMDD')), 'YYYYMMDD'), 'YYYY-MM-DD') AS "현POSITION_BAND승진일"
       ,TO_CHAR(TO_DATE(F_COM_GET_CURR_PERSONAL_BAND_YMD(K.ENTER_CD, K.SABUN, TO_CHAR(SYSDATE, 'YYYYMMDD')), 'YYYYMMDD'), 'YYYY-MM-DD') AS "현PERSONAL_BAND승진일"
       ,TO_CHAR(TO_DATE(F_COM_GET_CURR_JIKGUB_YMD(K.ENTER_CD, K.SABUN, TO_CHAR(SYSDATE, 'YYYYMMDD')), 'YYYYMMDD'), 'YYYY-MM-DD') AS "현JOB_BAND승진일"
       ,TO_CHAR(TO_DATE(F_COM_GET_CURR_JIKWEE_YMD(K.ENTER_CD, K.SABUN, TO_CHAR(SYSDATE, 'YYYYMMDD')), 'YYYYMMDD'), 'YYYY-MM-DD') AS "현KOREAN_TITLE승진일"
       ,TO_CHAR(TO_DATE(F_COM_GET_CURR_JIKCHAK_YMD(K.ENTER_CD, K.SABUN, TO_CHAR(SYSDATE, 'YYYYMMDD')), 'YYYYMMDD'), 'YYYY-MM-DD') AS "현TITLE승진일"
       ,TO_CHAR(TO_DATE(F_COM_GET_CURR_POSITION_TITLE_YMD(K.ENTER_CD, K.SABUN, TO_CHAR(SYSDATE, 'YYYYMMDD')), 'YYYYMMDD'), 'YYYY-MM-DD') AS "현POSITION_TITLE승진일"
       ,F_COM_GET_CAREER_CNT(K.ENTER_CD, K.SABUN, 'G', 'YYMM', '1', NULL, '@ssnLocaleCd@') AS "그룹근속기간"
       ,K.STF_TYPE AS "채용구분코드"
       ,(SELECT F_COM_GET_GRCODE_NAME(K.ENTER_CD, 'F10001', K.STF_TYPE, '@ssnLocaleCd@') FROM DUAL) AS "채용구분"
       ,K.EMP_TYPE AS "입사구분코드"
       ,K.EMP_TYPE_NM AS "입사구분"
       ,C.PAY_TYPE AS "급여유형코드"
       ,(SELECT F_COM_GET_GRCODE_NAME(C.ENTER_CD, 'H10110', C.PAY_TYPE, '@ssnLocaleCd@') FROM DUAL) AS "급여유형"
       ,TO_CHAR(TO_DATE(K.CON_S_YMD, 'YYYYMMDD'), 'YYYY-MM-DD') AS "계약시작일"
       ,TO_CHAR(TO_DATE(K.CON_E_YMD, 'YYYYMMDD'), 'YYYY-MM-DD') AS "계약종료일"
       ,K.FOREIGN_YN AS "외국인여부"
       ,K.NATIONAL_CD AS "국적코드"
       ,(SELECT F_COM_GET_GRCODE_NAME(K.ENTER_CD, 'H20290', K.NATIONAL_CD, '@ssnLocaleCd@') FROM DUAL) AS "국적명"
       ,TO_CHAR(TO_DATE(K.BIR_YMD, 'YYYYMMDD'), 'YYYY-MM-DD') AS "생년월일"
       ,F_COM_GET_AGE(K.ENTER_CD, K.BIR_YMD, K.RES_NO, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD'))) AS "나이"
       ,K.WED_YN AS "결혼여부"
       ,K.BLOOD_CD AS "혈액형"
       ,TCPN710.RET_PENTION_TYPE AS "퇴직연금유형코드"
       ,(SELECT F_COM_GET_GRCODE_NAME(K.ENTER_CD, 'H10170', TCPN710.RET_PENTION_TYPE, '@ssnLocaleCd@') FROM DUAL) AS "퇴직연금유형"
       ,F_COM_GET_CONT_ADDRESS(K.ENTER_CD, K.SABUN, 'OT') AS "사내전화번호"
       ,F_COM_GET_CONT_ADDRESS(K.ENTER_CD, K.SABUN, 'HT') AS "집전화번호"
       ,F_COM_GET_CONT_ADDRESS(K.ENTER_CD, K.SABUN, 'HP') AS "회사핸드폰"
       ,F_COM_GET_CONT_ADDRESS(K.ENTER_CD, K.SABUN, 'PH') AS "개인핸드폰"
       ,F_COM_GET_CONT_ADDRESS(K.ENTER_CD, K.SABUN, 'ET') AS "해외전화"
       ,F_COM_GET_CONT_ADDRESS(K.ENTER_CD, K.SABUN, 'IM') AS "메일주소"
       ,X.ACA_NM AS "최종학력"
       ,X.ACA_SCH_NM AS "학교명1"
       ,X.ACAMAJ_NM AS "전공1"
       ,X.ACA_YN_NM AS "졸업구분1"
       ,X.ACA_E_YM AS "졸업월1"
       ,H.ACA_SCH_NM AS "학교명2"
       ,H.ACAMAJ_NM AS "전공2"
       ,H.ACA_YN_NM AS "졸업구분2"
       ,H.ACA_E_YM AS "졸업월2"
       ,THRM121.TRANSFER_CD AS "병역전역구분코드"
       ,(SELECT F_COM_GET_GRCODE_NAME(THRM121.ENTER_CD, 'H20200', THRM121.TRANSFER_CD, '@ssnLocaleCd@') FROM DUAL) AS "병역전역구분"
       ,THRM121.ARMY_CD AS "군별코드"
       ,(SELECT F_COM_GET_GRCODE_NAME(THRM121.ENTER_CD, 'H20230', THRM121.ARMY_CD, '@ssnLocaleCd@') FROM DUAL) AS "군별"
       ,THRM121.ARMY_GRADE_CD AS "계급코드"
       ,(SELECT F_COM_GET_GRCODE_NAME(THRM121.ENTER_CD, 'H20220', THRM121.ARMY_GRADE_CD, '@ssnLocaleCd@') FROM DUAL) AS "계급"
       ,THRM121.ARMY_D_CD AS "병과코드"
       ,(SELECT F_COM_GET_GRCODE_NAME(THRM121.ENTER_CD, 'H20210', THRM121.ARMY_D_CD, '@ssnLocaleCd@') FROM DUAL) AS "병과"
       ,THRM121.ARMY_NO AS "군번"
       ,THRM121.ARMY_S_YMD AS "입대일"
       ,THRM121.ARMY_E_YMD AS "제대일"
       ,THRM121.ARMY_MEMO AS "면제사유"
       ,THRM123.ADDR1 || ' ' || THRM123.ADDR2 AS "주소"
       ,F_COM_GET_JIKJONG_CD(K.ENTER_CD, K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD'))) AS "직종코드"
       ,F_COM_GET_JIKJONG_NM(K.ENTER_CD, K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD')), '@ssnLocaleCd@') AS "직종"
       ,NVL(F_HRM_UNION_MEMBER_YN(K.ENTER_CD, K.SABUN, NVL(REPLACE('@viewSearchDate@', '-', ''), TO_CHAR(SYSDATE, 'YYYYMMDD'))), 'N') AS "노조가입여부"
       ,K.EXECUTIVE_YMD AS "임금피크제시작일"
       ,K.BIRTH_AREA AS "차량번호"
       ,K.GROWTH_AREA AS "차종"
       ,K.MY_WORK AS "FUNCTION_MANAGER"
       ,K.POORNATA_ID AS "POORNATA_ID"
       ,K.AD_ID AS "AD_ID"
       ,K.IHR_ID AS "IHR_ID"
       ,K.ENTER_CD AS "ENTER_CD"
       ,K.SABUN AS "SABUN"
       ,C.STATUS_CD AS "STATUS_CD"